#--------------------------------#
# MinigameTemplate by humandavey #
#--------------------------------#

countdown-seconds: 20
lobby-spawn:
  world: 'world'
  x: -28.0
  y: 117
  z: -18.0
  yaw: -45
  pitch: 0

arenas:
  0:
    game: 'BLOCK'
    world: 'world'
    x: -27.5
    y: 97
    z: 63.5
    yaw: -180
    pitch: 0